import "./globals.css";



export const metadata = {
  title: "AgroWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`max-w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
